branch-defaults:
  master:
    environment: production
    group_suffix: null
  staging:
    environment: staging
    group_suffix: null
  develop:
    environment: develop
global:
  application_name: graphql-node-server
  branch: null
  default_ec2_keyname: graphql-aws-eb
  default_platform: Node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
option_settings:
  aws:elasticbeanstalk:container:nodejs:
    NodeCommand: npm start
